"""Initial migration.

Revision ID: 2a1986e7c114
Revises: 19dd8061d944
Create Date: 2025-05-26 21:57:12.327585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1986e7c114'
down_revision = '19dd8061d944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entrance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('entrance')
        batch_op.drop_column('floor')

    # ### end Alembic commands ###
