"""notations new.

Revision ID: 92387f412b95
Revises: 0bd4bb68fc5f
Create Date: 2025-06-11 09:16:38.965529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92387f412b95'
down_revision = '0bd4bb68fc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_to_chat', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chat_article_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chat_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('chat_user_id')
        batch_op.drop_column('chat_article_id')
        batch_op.drop_column('redirect_to_chat')

    # ### end Alembic commands ###
